groups:
  - name: receipts_scanner_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighProcessingErrorRate
        expr: rate(processing_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High processing error rate detected"
          description: "Processing error rate is {{ $value }} errors/second"

      # Worker failures
      - alert: HighWorkerFailureRate
        expr: rate(celery_task_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Celery worker failure rate"
          description: "Worker failure rate is {{ $value }} failures/second"

      # Queue backlog
      - alert: LargeQueueBacklog
        expr: celery_active_workers > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Large task queue backlog"
          description: "{{ $value }} tasks in queue"

      # Low OCR confidence
      - alert: LowOCRConfidence
        expr: histogram_quantile(0.5, rate(ocr_confidence_score_bucket[10m])) < 0.5
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Low OCR confidence scores"
          description: "Median OCR confidence is {{ $value }}"

      # API response time
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile latency is {{ $value }}s"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.instance }} has been down for more than 2 minutes"

      # Model accuracy degradation
      - alert: ModelAccuracyDegraded
        expr: model_accuracy < 0.7
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Model accuracy has degraded"
          description: "Current accuracy is {{ $value }}, consider retraining"