global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'receipts-scanner'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application
  - job_name: 'receipts-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Celery workers
  - job_name: 'receipts-worker'
    static_configs:
      - targets: ['worker:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis exporter (if using redis-exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # MinIO metrics (if exposed)
  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s