global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']

  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:8002']

rule_files:
  - /etc/prometheus/alerts.yml
